### ISSUE TITLE
リアクション追加が反映されず、画面操作不能になる

### ISSUE THREAD

**Issue by miyacorata** [346design/twista.283.cloud#19]
## Summary
リアクションする際、選択・ランダムを問わず追加がその場では反映されず、リロードするまでスクロール以外のほとんどの画面操作を受け付けなくなる

リロードすると選択した(あるいはランダム追加した)リアクションは投稿に反映されている

ただしすでにつけられているリアクションを追加する(+からリアクションしない)場合は問題なくリアクションが追加できる

### フリーズ以降動作するもの
* 新規Post
* Renote
* 返信
### フリーズ以降動作しないもの
* ハイライト・見つけるなどの別ページへの遷移(アドレスバー書き換わりとページ先頭には戻る)
* リアクション追加ウィンドウのうち、絵文字入力部とランダムボタンが表示されない

## 確認環境
* ver 10.100.283-tf.92 (seabedhike)
* Windows10 1803 build 17134.706
* Google Chrome Stable 73.0.3683.103
* Google Chrome Canary 75.0.3761.0
* Firefox 67.0b9

**Comment by acid-chicken** [comment]
とりあえず以前のUIに差し戻しました。
