### ISSUE TITLE
🎂 brings &#8203;

### ISSUE THREAD

**Issue by miyacorata** [346design/twista.283.cloud#549]
Summary
==
投稿しようとする文章内に🎂(&.#127874; or &.#x1F382;)が含まれる場合、その直前の文字が絵文字であったときに&#8203;(ゼロ幅スペース)が混入する

Expected Behavior
--
```
🎉
🎂
```

Actual Behavior
--
```
🎉&#8203;
🎂
```

Environment
--
* twista - ver 10.102.283-mano.13 (seabedhike)
* Chrome(Stable) - Ver 79.0.3945.117

**Comment by acid-chicken** [comment]
ゼロ幅スペースが混入すること自体は仕様です。（Mastodon 等で絵文字が表示されない場合があるため）ただ、ゼロ幅スペースが誤って Twiemoji の URL にも混入しているのはバグです。

**Comment by miyacorata** [comment]
👍
